name: deployment notification
on: [deployment_status]

jobs:
  successful_deploy:
    if: ${{ github.event.deployment_status.state == 'success' }}
    name: successful_deploy
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message when deploy is successfully done
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: 🟢 ${{ github.event.deployment_status.description }}!
  unsuccessful_deploy:
    if: ${{ github.event.deployment_status.state == 'failure' || github.event.deployment_status.state == 'error'}}
    name: unsuccessful_deploy
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message when deploy fails
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: 🔴 ${{ github.event.deployment_status.description }}! \
            ${{ github.event.deployment_status.log_url }}
