name: deployment notification
on: [deployment_status]
jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            New release: ${{ github.event.head_commit.message }}
