name: deployment notification
on: [deployment_status]
jobs:
  deploy_status:
    name: successful_deploy
    if: github.event.deployment_status.state == "success"
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message when deploy is successfully done
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: 🛠 New Deployment DONE successfully!
