name: push notification
on:
  push:
    branches:
      - master

jobs:
  push_notification:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            🛠 New Commit: ${{ github.event.commits[0].message }}